### PR TITLE
Support aws_autoscaling_notification(s)

### PR DESCRIPTION
**Pull request by nishigori**
Hope to creating resource `aws_autoscaling_notification` on module of cluster

And this resource(s) as optional (as the defalut, no creation)

## References

- https://www.terraform.io/docs/providers/aws/r/autoscaling_notification.html
- https://docs.aws.amazon.com/AutoScaling/latest/APIReference/API_DescribeNotificationConfigurations.html
- https://docs.aws.amazon.com/AutoScaling/latest/APIReference/API_NotificationConfiguration.html

### CODE REVIEW

**Comment by nishigori** [comment]
@cynipe r?

**Comment by cynipe** [comment]
👀

**Comment by cynipe** [comment]
@pupuko r+

**Comment by nishigori** [comment]
thx~

(btw, what's `@popuko` ?

**Comment by cynipe** [comment]
nvm, lgtm

**Pull request merged**
