### PR TITLE
enable to explicitly set containers family name

### PR DESCRIPTION
**Pull request by YOwatari**
I want to set containers family (task definition family) and name separately.
For example,  I set my application name to containers family, and middleware name to containers name.

So, I propose that we can explicitly set containers family name.
If you dont give contianers family name, implicitly set containers name to containers family name as before.

### CODE REVIEW

**Comment by nishigori** [comment]
Thanks your proposal !!

> If you dont give contianers family name, implicitly set containers name to containers family name as before.

mm.. I don't want to split result that ocrrued by variable arguments.
Would you changed `family = "${var.container_family} ` ? that is so simple.

The abobe stmt has bc break but this module is alpha version.
I don't care yet :P

**Comment by YOwatari** [comment]
> The abobe stmt has bc break but this module is alpha version.

I agree your opinion.
I concerned changing includes bc break, but I dont mind it.

**Comment by nishigori** [comment]
LGTM, thank you

**Comment by nishigori** [comment]
we just release [v0.0.4](https://github.com/voyagegroup/tf_aws_ecs/releases/tag/v0.0.4)

**Pull request merged**
